Preview docs from different branches
onflow/developer-portal pull request #660
Opened 2022-09-16 15:54 UTC by joekrill

Closes #654 

This allows specifying a `preview=` query string parameter which takes a ref or branch name and will fetch docs from that branch/ref instead of the one specified by the doc collection manifest.

It looks something like this:

<img width="1217" alt="Screen Shot 2022-09-16 at 11 40 25 AM" src="https://user-images.githubusercontent.com/393220/190679698-c75b4986-3d2f-477b-a063-c1f5398ee3bb.png">

All relative URLs within that document collection also include the `preview=` parameter: sidebar links, "internal" doc links, next/previous links, asset URLs. 

If the branch does not exist and error indicates that:
 
<img width="1221" alt="Screen Shot 2022-09-16 at 11 40 34 AM" src="https://user-images.githubusercontent.com/393220/190679940-8cd049cd-0c64-4188-817d-b932ce731f5f.png">

2022-09-16 18:05 UTC, 10thfloor requested changes
Nice to see this working. Could we adjust the banner colour to something more neutral, maybe light blue or green? Red feels scary. 😅

2022-09-16 19:42 UTC, joekrill commented
sure - how's cyan? 

<img width="1218" alt="Screen Shot 2022-09-16 at 3 40 56 PM" src="https://user-images.githubusercontent.com/393220/190717980-b271dca9-2060-4c28-92b5-c4976fcde016.png">

2022-09-19 18:41 UTC, 10thfloor commented
@joekrill this is great. Are you planning another PR that posts links to new docs in Pull Request comments?

2022-09-19 18:44 UTC, 10thfloor requested changes
Cyan is nice. Omit the hash from the preview banner as well. The banner should have a _link_ to the in-progress document on Github.

The text should read: "You are viewing an unpublished preview. View page in GitHub."
And the "View page in Github" should be a link, with the same icon for external links we use elsewhere.

2022-09-20 13:57 UTC, joekrill commented
Sorry @10thfloor I guess I accidentally edited _your_ reply instead of _adding_ my reply? I have no idea how that happened, that was totally unintentional.

2022-09-21 17:30 UTC, 10thfloor commented
> > @joekrill I was also thinking this over more and was wondering why we decided to use the commit hash?
> 
> Actually any ref will work - commit hash, branch name, tag, etc...
> 
> > Can we use the PR number instead of a sha? so the query string would be ?pr=420 instead of preview=sha ?
> 
> It is _possible_, But:
> 
> 1. We'd need to make an extra API call to Github on every request to determine the head ref of that PR.
> 2. It may not be possible to determine the PR at the time we receive the webhook in which we generate the preview URLs automatically. That webhook gets sent when a _branch_ is changed, and that may have zero, one, or more PRs associated with it.
> 
> > I think this is much better from an end-user perspective. Finding the PR number is more straightforward than the commit hash.
> 
> I suggest that we generate preview URLs using branch names when possible (with fallback to SHA), for now, and if we want to use PR numbers we implement that as an enhancement.

Ok, yes branch names are also user friendly, and I think better than the sha and having both means to access a preview is great.

2022-09-23 21:45 UTC, 10thfloor approved these changes

2022-09-23 21:46 UTC, merged